name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.5, 3.8]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run Tests
      uses: ./.github/actions/test
      with:
        python-version: ${{ matrix.python-version }}
